[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "src/netlify/edge-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/api/ophelia"
  function = "ophelia"
